import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Socials from "@/components/Socials";
import RootStyleRegistry from "./emotion";

const space_grotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata = {
  title: "Esports Dao",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="root" className={space_grotesk.className}>
        <Navbar />
        <Socials />
        <div className=" mx-auto mb-64 pt-[84px] xl:pt-[154px]">
          <main className="px-5 md:px-12">
            <RootStyleRegistry>{children}</RootStyleRegistry>
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
